name: CI

on:
  push:
    branches-ignore:
      - 'rc-**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: npm install

      - name: Test
        run: npm run test

      - name: ESLint
        run: npm run lint
